<a href="https://colab.research.google.com/github/camacw92/Capstone--Daily-Inmates-in-Custody/blob/master/Capstone_8_29_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#DATA IMPORT
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

df=pd.read_csv('https://raw.githubusercontent.com/DMDataAnalytics/Inmates/master/Daily_Inmates_In_Custody%20Raw.csv')
df

#DATA Cleaning
#df.head()
#df.dtypes
#df.describe()


df2=df.rename(columns={'ADMITTED_DT':'Date Admitted','BRADH':'Under Mental Observation','SRG_FLG':'Affilated with Gang'	})
df2
#Dropping DISCHARGED_DT column since it has no values in it
df3= df2.drop(['DISCHARGED_DT','SEALED'], axis=1)


#DATA Cleaning
#df2.head()
#df2.dtypes
#df2.describe()


df4= (df3.dropna())
df4




#Code to Export Cleaned Data On To Local Machine For Tableau 
from google.colab import files
df4.to_csv('CleanedInmateDataset.csv') 
files.download('CleanedInmateDataset.csv')

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
#DATA IMPORT
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

df=pd.read_csv('https://raw.githubusercontent.com/DMDataAnalytics/Inmates/master/Daily_Inmates_In_Custody%20Raw.csv')
df

#DATA Cleaning
#df.head()
#df.dtypes
#df.describe()


df2=df.rename(columns={'ADMITTED_DT':'Date Admitted','BRADH':'Under Mental Observation','SRG_FLG':'Affilated with Gang'	})
df2
#Dropping DISCHARGED_DT column since it has no values in it
df3= df2.drop(['DISCHARGED_DT','SEALED'], axis=1)


#DATA Cleaning
#df2.head()
#df2.dtypes
#df2.describe()


df4= (df3.dropna())
df4

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

      INMATEID    Date Admitted  ...  TOP_CHARGE INFRACTION
0     20209345   2/15/2020 1:11  ...  110-125.25          N
1       133023  8/24/2018 16:36  ...      125.25          Y
2        23087  7/13/2020 23:45  ...      160.15          Y
3     10003128   8/7/2020 12:40  ...       215.5          N
4     20208697   5/1/2020 15:27  ...       155.3          Y
...        ...              ...  ...         ...        ...
4127    162948   2/21/2019 0:51  ...      130.96          N
4128  20132871  5/14/2014 15:59  ...      125.25          Y
4129  20205597  7/10/2019 18:13  ...      125.25          Y
4130  20194765   5/11/2018 1:04  ...      125.25          Y
4131  20204014   5/2/2019 15:52  ...      220.41          N

[3756 rows x 11 columns]